#!/usr/bin/env bash

main() {
  webpack-dev-server --inline
}

fix() {
  echo "fix angular"
  sed -i '$s/.*/exports.__esModule = true;/' node_modules/angular2/{core.js,common.js,router.js,http.js,platform/browser.js,src/common/forms/directives/control_value_accessor.js}
}

case "$1" in
  "" ) main ;;
  fix ) fix ;;
esac
